# Generated by Django 4.1.6 on 2023-02-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_projectdeveloper_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeveloper',
            name='project_hire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_hire', to='WebApp.projecthire'),
        ),
    ]
