# Generated by Django 4.1.6 on 2023-02-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_alter_projectdeveloper_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeveloper',
            name='role',
            field=models.ManyToManyField(related_name='role_r_name', to='WebApp.roll'),
        ),
    ]
